# Generated by Django 5.1.1 on 2024-09-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryHello', '0002_enrollment_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'abc_Table',
                'ordering': ['name'],
            },
        ),
    ]
